"""
trace_builder.py — Builds the cross-reference traceability map between artifacts.

Phase 2 of the HTML export workflow.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).parent))

from utils import extract_references


def load_manifest(manifest_path: Path) -> dict:
    """Load the manifest.yaml generated by doc_scanner."""
    with open(manifest_path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def build_trace_map(manifest: dict, doc_root: Path) -> dict:
    """
    Build the cross-reference traceability map.

    For each artifact, maps:
    - forward_refs: references this artifact MAKES to others
    - back_refs: references OTHER artifacts make to this one
    - gaps: broken references (pointing to nonexistent targets)
    """
    all_artifacts = manifest.get("all_artifacts", [])

    # Index artifacts by filename (without extension) for fast lookup
    artifact_index: dict[str, dict] = {}
    for art in all_artifacts:
        stem = Path(art["filename"]).stem.lower()
        artifact_index[stem] = art
        # Also index without numeric prefix for partial lookups
        if art.get("type") in ("req", "tec_req", "apf_req", "cri_req"):
            # Index as "req-0001" (with number)
            artifact_index[stem] = art

    # Index by normalized title
    title_index: dict[str, dict] = {}
    for art in all_artifacts:
        title_key = art.get("title", "").lower().strip()
        if title_key:
            title_index[title_key] = art

    trace_map: dict[str, dict] = {}
    all_gaps: list[dict] = []

    for art in all_artifacts:
        art_file = art["file"]
        art_stem = Path(art["filename"]).stem.lower()

        try:
            content = (doc_root / art_file).read_text(encoding="utf-8")
        except Exception:
            content = ""

        refs = extract_references(content)

        # Convert references to filenames
        forward_refs: list[dict] = []
        gaps: list[dict] = []

        # References to req-XXXX
        for ref_req in refs.get("req", []):
            target_stem = ref_req.lower()
            found = _find_artifact(target_stem, artifact_index)
            if found:
                forward_refs.append({
                    "type": "req",
                    "ref": ref_req,
                    "file": found["file"],
                    "title": found.get("title", ""),
                })
            else:
                gaps.append({
                    "type": "req",
                    "ref": ref_req,
                    "reason": "Referenced artifact not found",
                })

        # References to tec-req-XXXX
        for ref_tec in refs.get("tec_req", []):
            target_stem = ref_tec.lower()
            found = _find_artifact(target_stem, artifact_index)
            if found:
                forward_refs.append({
                    "type": "tec_req",
                    "ref": ref_tec,
                    "file": found["file"],
                    "title": found.get("title", ""),
                })
            else:
                gaps.append({
                    "type": "tec_req",
                    "ref": ref_tec,
                    "reason": "Referenced technical document not found",
                })

        # References to APIs
        for ref_api in refs.get("api", []):
            target_stem = ref_api.lower()
            found = _find_artifact(target_stem, artifact_index)
            if found:
                forward_refs.append({
                    "type": "api",
                    "ref": ref_api,
                    "file": found["file"],
                    "title": found.get("title", ""),
                })
            else:
                gaps.append({
                    "type": "api",
                    "ref": ref_api,
                    "reason": "Referenced API not found",
                })

        # References to ER diagrams
        for ref_der in refs.get("der", []):
            target_stem = ref_der.lower()
            found = _find_artifact(target_stem, artifact_index)
            if found:
                forward_refs.append({
                    "type": "der",
                    "ref": ref_der,
                    "file": found["file"],
                    "title": found.get("title", ""),
                })
            else:
                gaps.append({
                    "type": "der",
                    "ref": ref_der,
                    "reason": "Referenced ER diagram not found",
                })

        # References to data dictionaries
        for ref_did in refs.get("did", []):
            target_stem = ref_did.lower()
            found = _find_artifact(target_stem, artifact_index)
            if found:
                forward_refs.append({
                    "type": "did",
                    "ref": ref_did,
                    "file": found["file"],
                    "title": found.get("title", ""),
                })
            else:
                gaps.append({
                    "type": "did",
                    "ref": ref_did,
                    "reason": "Referenced data dictionary not found",
                })

        # References to class diagrams
        for ref_dcl in refs.get("dcl", []):
            target_stem = ref_dcl.lower()
            found = _find_artifact(target_stem, artifact_index)
            if found:
                forward_refs.append({
                    "type": "dcl",
                    "ref": ref_dcl,
                    "file": found["file"],
                    "title": found.get("title", ""),
                })
            else:
                gaps.append({
                    "type": "dcl",
                    "ref": ref_dcl,
                    "reason": "Referenced class diagram not found",
                })

        # References to RF/RN (list only, no file needed)
        for ref_rf in refs.get("rf", []):
            forward_refs.append({
                "type": "rf",
                "ref": ref_rf,
                "file": "",
                "title": f"Functional Requirement {ref_rf}",
            })
        for ref_rn in refs.get("rn", []):
            forward_refs.append({
                "type": "rn",
                "ref": ref_rn,
                "file": "",
                "title": f"Business Rule {ref_rn}",
            })

        trace_map[art_file] = {
            "artifact": art,
            "forward_refs": forward_refs,
            "gaps": gaps,
        }
        all_gaps.extend(gaps)

    # Build back_refs (who points to me)
    for art_file, trace_info in trace_map.items():
        back_refs: list[dict] = []
        for other_file, other_trace in trace_map.items():
            if other_file == art_file:
                continue
            for ref in other_trace["forward_refs"]:
                if ref.get("file") == art_file:
                    back_refs.append({
                        "type": ref["type"],
                        "ref": ref["ref"],
                        "source_file": other_file,
                        "source_title": other_trace["artifact"].get("title", ""),
                    })
                    break
        trace_info["back_refs"] = back_refs

    return {
        "trace_map": trace_map,
        "gaps": all_gaps,
        "total_artifacts": len(all_artifacts),
        "total_references": sum(
            len(t["forward_refs"]) for t in trace_map.values()
        ),
        "total_gaps": len(all_gaps),
    }


def _find_artifact(stem: str, index: dict[str, dict]) -> dict | None:
    """Search for an artifact by filename stem in the index."""
    # Exact match
    if stem in index:
        return index[stem]
    # Partial match (e.g., "req-0001" in "req-0001-requirement-name")
    for key, art in index.items():
        if key.startswith(stem):
            return art
    return None


def generate_traceability_matrix(trace_result: dict) -> str:
    """Generate HTML for the global traceability matrix."""
    trace_map = trace_result["trace_map"]

    rows = []
    for art_file, info in sorted(trace_map.items()):
        art = info["artifact"]
        fwd = len(info["forward_refs"])
        bwd = len(info["back_refs"])
        gaps = len(info["gaps"])

        status_class = "trace-status-ok" if gaps == 0 else "trace-status-missing"
        status_text = "OK" if gaps == 0 else f"{gaps} gap(s)"

        rows.append(f"""        <tr>
          <td><span class="doc-badge doc-badge-{_badge_class(art.get('type', ''))}">{art.get('type', '').upper()}</span></td>
          <td><a href="{_html_path(art_file)}">{art.get('title', art['filename'])}</a></td>
          <td class="text-center">{fwd}</td>
          <td class="text-center">{bwd}</td>
          <td class="{status_class} text-center">{status_text}</td>
        </tr>""")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Traceability Matrix</title>
  <link rel="stylesheet" href="../css/integrated-theme.css">
</head>
<body>
  <div class="md-content" style="max-width: 1200px; margin: 0 auto; padding: 2rem;">
    <h1>Cross-Reference Traceability Matrix</h1>
    <p>Total artifacts: <strong>{trace_result['total_artifacts']}</strong> |
       Total references: <strong>{trace_result['total_references']}</strong> |
       Gaps: <strong>{trace_result['total_gaps']}</strong></p>

    <table class="trace-matrix">
      <thead>
        <tr>
          <th>Type</th>
          <th>Artifact</th>
          <th>References (→)</th>
          <th>Referenced by (←)</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
{chr(10).join(rows)}
      </tbody>
    </table>

    {"<h2>Gaps Found</h2><ul>" + "".join(f'<li><strong>{g["ref"]}</strong> ({g["type"]}): {g["reason"]}</li>' for g in trace_result["gaps"]) + "</ul>" if trace_result["gaps"] else "<p>No gaps found.</p>"}
  </div>
</body>
</html>"""


def _badge_class(artifact_type: str) -> str:
    """Return CSS class for an artifact type badge."""
    mapping = {
        "req": "req",
        "tec_req": "api",
        "apf_req": "dados",
        "cri_req": "proc",
        "api": "api",
        "der": "dados",
        "did": "dados",
        "dcl": "dados",
        "min": "api",
        "vis": "req",
        "apr_req": "proc",
    }
    return mapping.get(artifact_type, "req")


def _html_path(art_file: str) -> str:
    """Convert relative .md path to .html path for links."""
    p = Path(art_file)
    return str(p.with_suffix(".html"))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build cross-reference traceability map"
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        required=True,
        help="Path to manifest.yaml",
    )
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Documentation root directory",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Output path for traceability.json",
    )
    args = parser.parse_args()

    if not args.manifest.exists():
        print(f"ERROR: Manifest '{args.manifest}' not found.")
        print("Run doc_scanner.py first.")
        sys.exit(1)

    print("[1/3] Loading manifest...")
    manifest = load_manifest(args.manifest)

    print("[2/3] Building traceability map...")
    trace_result = build_trace_map(manifest, args.input)

    print(f"  Artifacts: {trace_result['total_artifacts']}")
    print(f"  References: {trace_result['total_references']}")
    print(f"  Gaps: {trace_result['total_gaps']}")

    if trace_result["gaps"]:
        print("\n  [GAPS FOUND]")
        for gap in trace_result["gaps"]:
            print(f"    - {gap['ref']} ({gap['type']}): {gap['reason']}")

    print("[3/3] Saving traceability.json...")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(trace_result, f, ensure_ascii=False, indent=2)

    # Also generate the HTML matrix
    matrix_html = generate_traceability_matrix(trace_result)
    matrix_path = args.output.parent / "matrix.html"
    with open(matrix_path, "w", encoding="utf-8") as f:
        f.write(matrix_html)

    print(f"  Traceability saved to: {args.output}")
    print(f"  HTML matrix saved to: {matrix_path}")


if __name__ == "__main__":
    main()
